server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/taxi_db
    username: taxi_user
    password: taxi_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379

user.service.url: http://127.0.0.1:8081

logging:
  level:
    com.taxi.trip: DEBUG